-- ============================================================
-- SpaceFurnio E-Commerce Products Database
-- Migration 004: Seed Design-Style Products & All Images/Colors
-- ============================================================
BEGIN;

-- Design-Style Products (listing_type = 'design-style')

INSERT INTO products (name, slug, price_cents, brand_id, style_id, room_id, material_id, listing_type, rating, review_count, popularity, href, created_at) VALUES
('Concrete Block Coffee Table','concrete-block-coffee-table',64900,(SELECT id FROM brands WHERE slug='raw-design'),(SELECT id FROM styles WHERE slug='brutalist'),(SELECT id FROM rooms WHERE slug='living-room'),(SELECT id FROM materials WHERE name='Concrete'),'design-style',4.3,76,82,'./201','2024-01-20'),
('Steel Frame Bookshelf','steel-frame-bookshelf',89900,(SELECT id FROM brands WHERE slug='industrial-form'),(SELECT id FROM styles WHERE slug='brutalist'),(SELECT id FROM rooms WHERE slug='study'),(SELECT id FROM materials WHERE name='Steel & Wood'),'design-style',4.5,123,89,'./202','2024-02-01'),
('Clean Line Dining Table','clean-line-dining-table',119900,(SELECT id FROM brands WHERE slug='minimal-living'),(SELECT id FROM styles WHERE slug='minimalist'),(SELECT id FROM rooms WHERE slug='dining-room'),(SELECT id FROM materials WHERE name='White Oak'),'design-style',4.7,189,95,'./203','2024-01-15'),
('Simple Storage Bench','simple-storage-bench',29900,(SELECT id FROM brands WHERE slug='less-is-more'),(SELECT id FROM styles WHERE slug='minimalist'),(SELECT id FROM rooms WHERE slug='bedroom'),(SELECT id FROM materials WHERE name='Plywood'),'design-style',4.2,145,78,'./204','2024-02-08'),
('Reclaimed Wood Console','reclaimed-wood-console',74900,(SELECT id FROM brands WHERE slug='eco-furniture'),(SELECT id FROM styles WHERE slug='sustainable'),(SELECT id FROM rooms WHERE slug='living-room'),(SELECT id FROM materials WHERE name='Reclaimed Wood'),'design-style',4.6,167,91,'./205','2024-01-28'),
('Bamboo Desk Organizer','bamboo-desk-organizer',8900,(SELECT id FROM brands WHERE slug='green-office'),(SELECT id FROM styles WHERE slug='sustainable'),(SELECT id FROM rooms WHERE slug='home-office'),(SELECT id FROM materials WHERE name='Bamboo'),'design-style',4.4,234,86,'./206','2024-02-12'),
('Algorithmic Wall Art','algorithmic-wall-art',129900,(SELECT id FROM brands WHERE slug='digital-craft'),(SELECT id FROM styles WHERE slug='parametric'),(SELECT id FROM rooms WHERE slug='living-room'),(SELECT id FROM materials WHERE name='3D Printed Polymer'),'design-style',4.1,45,73,'./207','2024-01-25'),
('Geometric Room Divider','geometric-room-divider',89900,(SELECT id FROM brands WHERE slug='form-function'),(SELECT id FROM styles WHERE slug='parametric'),(SELECT id FROM rooms WHERE slug='open-space'),(SELECT id FROM materials WHERE name='Metal'),'design-style',4.3,67,79,'./208','2024-02-05'),
('Imperfect Ceramic Vase','imperfect-ceramic-vase',14900,(SELECT id FROM brands WHERE slug='wabi-ceramics'),(SELECT id FROM styles WHERE slug='wabi-sabi'),(SELECT id FROM rooms WHERE slug='any-room'),(SELECT id FROM materials WHERE name='Stoneware'),'design-style',4.5,198,88,'./209','2024-01-18'),
('Weathered Wood Stool','weathered-wood-stool',19900,(SELECT id FROM brands WHERE slug='natural-living'),(SELECT id FROM styles WHERE slug='wabi-sabi'),(SELECT id FROM rooms WHERE slug='any-room'),(SELECT id FROM materials WHERE name='Aged Wood'),'design-style',4.2,112,75,'./210','2024-02-14'),
('Ornate Wooden Armchair','ornate-wooden-armchair',149900,(SELECT id FROM brands WHERE slug='heritage-furniture'),(SELECT id FROM styles WHERE slug='traditional'),(SELECT id FROM rooms WHERE slug='living-room'),(SELECT id FROM materials WHERE name='Mahogany'),'design-style',4.8,89,94,'./211','2024-01-12'),
('Classic Persian-Style Rug','classic-persian-style-rug',89900,(SELECT id FROM brands WHERE slug='traditional-textiles'),(SELECT id FROM styles WHERE slug='traditional'),(SELECT id FROM rooms WHERE slug='living-room'),(SELECT id FROM materials WHERE name='Wool'),'design-style',4.6,156,87,'./212','2024-02-03'),
('Retro Bar Cart','retro-bar-cart',54900,(SELECT id FROM brands WHERE slug='vintage-revival'),(SELECT id FROM styles WHERE slug='vintage-retro'),(SELECT id FROM rooms WHERE slug='dining-room'),(SELECT id FROM materials WHERE name='Brass & Glass'),'design-style',4.4,134,83,'./213','2024-01-30'),
('Sunburst Mirror','sunburst-mirror',32900,(SELECT id FROM brands WHERE slug='retro-reflections'),(SELECT id FROM styles WHERE slug='vintage-retro'),(SELECT id FROM rooms WHERE slug='living-room'),(SELECT id FROM materials WHERE name='Metal & Mirror'),'design-style',4.3,178,81,'./214','2024-02-09'),
('Victorian Velvet Sofa','victorian-velvet-sofa',229900,(SELECT id FROM brands WHERE slug='royal-comfort'),(SELECT id FROM styles WHERE slug='victorian'),(SELECT id FROM rooms WHERE slug='living-room'),(SELECT id FROM materials WHERE name='Velvet & Carved Wood'),'design-style',4.7,67,92,'./215','2024-01-22'),
('Ornate Gilt Mirror','ornate-gilt-mirror',79900,(SELECT id FROM brands WHERE slug='victorian-elegance'),(SELECT id FROM styles WHERE slug='victorian'),(SELECT id FROM rooms WHERE slug='bedroom'),(SELECT id FROM materials WHERE name='Carved Wood & Gold Leaf'),'design-style',4.5,89,78,'./216','2024-02-07'),
('Zen Platform Bed','zen-platform-bed',99900,(SELECT id FROM brands WHERE slug='peaceful-sleep'),(SELECT id FROM styles WHERE slug='japandi'),(SELECT id FROM rooms WHERE slug='bedroom'),(SELECT id FROM materials WHERE name='Oak & Linen'),'design-style',4.6,203,93,'./217','2024-01-15'),
('Minimalist Tea Table','minimalist-tea-table',39900,(SELECT id FROM brands WHERE slug='serene-living'),(SELECT id FROM styles WHERE slug='japandi'),(SELECT id FROM rooms WHERE slug='living-room'),(SELECT id FROM materials WHERE name='Ash Wood'),'design-style',4.4,167,85,'./218','2024-02-11'),
('Moroccan Pouf Ottoman','moroccan-pouf-ottoman',18900,(SELECT id FROM brands WHERE slug='desert-dreams'),(SELECT id FROM styles WHERE slug='moroccan'),(SELECT id FROM rooms WHERE slug='living-room'),(SELECT id FROM materials WHERE name='Leather'),'design-style',4.3,245,87,'./219','2024-01-28'),
('Geometric Tile Side Table','geometric-tile-side-table',44900,(SELECT id FROM brands WHERE slug='marrakech-modern'),(SELECT id FROM styles WHERE slug='moroccan'),(SELECT id FROM rooms WHERE slug='living-room'),(SELECT id FROM materials WHERE name='Ceramic Tile & Metal'),'design-style',4.5,132,89,'./220','2024-02-13');

COMMIT;
